from OpenGL.GL import \
    glBindTexture, \
    glTexParameteri, \
    glTexImage2D, \
    glGenLists, \
    glFrontFace, \
    glEnable, \
    glDisable, \
    glNewList, \
    glEndList, \
    glBegin, \
    glEnd, \
    glVertex3fv, \
    glNormal3fv, \
    glTexCoord2fv, \
    glGenTextures, \
    glShadeModel, \
    GL_TEXTURE_2D, \
    GL_TEXTURE_MIN_FILTER, \
    GL_TEXTURE_MAG_FILTER, \
    GL_LINEAR, \
    GL_RGBA, \
    GL_UNSIGNED_BYTE, \
    GL_POLYGON, \
    GL_CCW, \
    GL_COMPILE, \
    GL_COLOR_MATERIAL, \
    GL_DEPTH_TEST, \
    GL_CULL_FACE, \
    GL_SMOOTH
